token: put your token here
owners:
  - put your id here
dbUri: sqlite:bot.db # or use another
webhookUrl: put your cmd logs webhook url here
defaultColor: 0x9f00ff # pretty self-explanatory
debug: false # pretty self-explanatory too
lavalinkNodes:
  - host: localhost
    port: 2333
    password: "youshallnotpass"