token: put your token here
owners:
  - put your id here
dbUri: sqlite:bot.db # or use another
webhookID: put your cmd logs webhook id here
webhookToken: pretty self-explanatory
defaultColor: 0x9f00ff # pretty self-explanatory
debug: false # pretty self-explanatory too
lavalinkNodes:
  - host: localhost
    port: 2333
    password: "youshallnotpass"
githubApiKey: insert your github api key here